config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'register' => 'login#register'
  post 'register'=> 'login#register'

  get 'logout' => 'login#logout'
  get 'login' => 'login#index'
  post 'login' => 'login#login'
  resources :login
  resources :dashboard
  resources :sign_in
  devise_for :users, :controllers => {:sessions => "sign_in"}
  devise_for :books
  resources :home
  resources :users
  resources :books

  namespace :api , defaults: {format: :json} do
    namespace :v1 do
      resources :users, :only => [:index, :show, :create, :update, :destroy]
      resources :books, :only => [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token
  belongs_to :user

  private
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists? (access_token = self.access_token)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :api_key
  has_many :books
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
respond_to :json
before_action :restrict_access

  def index
    respond_with Book.all
  end

  def show
    respond_with Book.find(params[:id])
  end

  def create
    book = Book.new(book_params)
    if book.save
      render json: book, status: 201
    else
      render json: {errors: book.errors}, status: 422
    end
  end

  def update
    book = Book.find(params[:id])
    #check admin or current user
    if check_admin == true || check_current_user(book.user_id)
        if book.update(book_params_update)
          render json: book, status: 200
        else
          render json: {errors: book.errors},status: 422
        end
    else
      render json: "Access denied", status: 401
    end
  end

  def destroy
    book = Book.find(params[:id])
    if check_admin == true || check_current_user(book.user_id)
      book.destroy
      head 204
    else
      render json: "Access denied", status: 401
    end
  end

  private
  def book_params
    params.require(:book).permit(:user_id, :title, :description)
  end

  private
  def book_params_update
    params.require(:book).permit(:title, :description)
  end
# Check Admin Authentication
def check_admin
  authenticate_or_request_with_http_token do | token , options |
    if (ApiKey.find_by access_token: token).role.eql? "admin"
      return true
    else
      return false
    end
  end
end

# Check current User
def check_current_user (userID)
  authenticate_or_request_with_http_token do | token , options |
    if (ApiKey.find_by access_token: token).user_id.eql? userID
      return true
    else
      return false
    end
  end
end
  private
  def restrict_access
    authenticate_or_request_with_http_token do | token , options |
      ApiKey.exists?(access_token: token)
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  respond_to :json
  before_action :restrict_access , :except => [ :create]

  def index
    if check_admin == true
      respond_with User.all
    else
      render json: "Access Denied", status: 401
    end
  end

  def show
    user = User.find(params[:id])
    if check_admin == true || check_current_user(user.id) == true
      respond_with user
    else
      render json: "Access Denied", status: 401
    end
  end

  def create
    user = User.new(user_params)
      if user.save
        render json: user, status: 200
      else
        render json: {errors: user.errors}, status: 422
      end
  end

  def update
    user = User.find(params[:id])
    # Check Admin Authentication or Current User
    if check_admin == true || check_current_user(user.id) == true
      if user.update(user_params_update)
        render json: user, status: 200
      else
        render json: {errors: user.errors},status: 422
      end
    end
  end

  def destroy
    user = User.find(params[:id])
    # Check Admin Authentication or Current User
    if check_admin == true || check_current_user(user.id) == true
      ApiKey.delete_all(user_id: user.id)
      Book.delete_all(user_id:user.id)
      user.destroy
      render json: "User deleted", status: 204
    else
      render json: "Access denied", status: 401
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :role, :name)
  end

  private
  def user_params_update
    params.require(:user).permit(:email, :role, :name)
  end


  private
    # Post with token on header
    # def restrict_access
    # api_key = ApiKey.find_by_access_token(params[:access_token])
    # head unauthorized unless api_key
    # end
  def restrict_access
     authenticate_or_request_with_http_token do | token , options |
        ApiKey.exists?(access_token: token)
     end
  end

    # Check Admin Authentication
  def check_admin
    authenticate_or_request_with_http_token do | token , options |
      if (ApiKey.find_by access_token: token).role.eql? "admin"
        return true
      else
        return false
      end
    end
  end

  # Check current User
  def check_current_user (userID)
    authenticate_or_request_with_http_token do | token , options |
      if (ApiKey.find_by access_token: token).user_id.eql? userID
        return true
      else
        return false
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to controller: 'dashboard', action: 'index'
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
  def register
    user = User.find_by email: params[:email]
    if user
      redirect_to '/users/sign_in'
    end
  end
end

app/controllers/sign_in_controller.rb
class SignInController <  Devise::SessionsController
  def create
    ApiKey.create(user_id: current_user.id, role: current_user.role) unless current_user.nil?
    super
  end

  def destroy
    ApiKey.delete_all(user_id: current_user.id)
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<style>
  .custab{
    border: 1px solid #ccc;
    padding: 5px;
    margin: 5% 0;
    box-shadow: 3px 3px 2px #ccc;
    transition: 0.5s;
  }
  .custab:hover{
    box-shadow: 3px 3px 0px transparent;
    transition: 0.5s;
  }
</style>

<div id="token" style="display: none" ><%= current_user.api_key.access_token %></div>
<div id="userID" style="display: none" ><%= current_user.id %></div>
<div id="userRole" style="display: none" ><%= current_user.role %></div>

<div class="container">
  <div class="row col-md-10 custyle">
    <table class="table table-striped custab">
      <thead>
      <a id="addBook" data-toggle="modal" data-target="#addBookModel" class="btn btn-primary btn-md pull-right"><b>+</b> Add book</a>
      <tr>
        <th class='text-center'>ID</th>
        <th>Title</th>
        <th>Description</th>
        <th>User ID</th>
        <th class="text-center">Action</th>
      </tr>
      </thead>
      <tbody id="table_content_book">

      </tbody>
    </table>
  </div>
</div>


<!--Add User Model-->
<div class="modal fade" id="addBookModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Create book</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="title" class="control-label">Title:</label>
            <input type="text" class="form-control" id="title" name="title">
          </div>

          <div class="form-group">
            <label for="email" class="control-label">Description:</label>
            <textarea type="text" class="form-control" id="description" name="description"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="addBookButton" type="button" class="btn btn-primary">Create book </button>
      </div>
    </div>
  </div>
</div>

<!--Edit book Model-->
<div class="modal fade" id="editBookModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Edit book</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="title" class="control-label">Title:</label>
            <input type="text" class="form-control" id="title" name="title">
          </div>

          <div class="form-group">
            <label for="email" class="control-label">Description:</label>
            <textarea type="text" class="form-control" id="description" name="description"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="editBookButton" type="button" class="btn btn-primary">Edit book </button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="profileBook" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Book Detail</h4>
      </div>
      <div class="modal-body">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title" class="Book_Title"></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-3 col-lg-3 " align="center"> <img alt="book Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
              <div class=" col-md-9 col-lg-9 ">
                <table class="table table-book-information">
                  <tbody>
                  <tr>
                    <td> ID:</td>
                    <td  class="bookID"></td>
                  </tr>
                  <tr>
                    <td> Title:</td>
                    <td  class="bookTitle"></td>
                  </tr>
                  <tr>
                    <td> Description:</td>
                    <td  class="bookDescription"></td>
                  </tr>
                  <tr>
                    <td> User Owner:</td>
                    <td  class="bookUserID"></td>
                  </tr>
                  <tr>
                    <td > Created at : </td>
                    <td class="bookCreateDate"></td>
                  </tr>
                  <tr>
                    <td > Modified at: </td>
                    <td class="bookModifyDate"></td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <h1> Welcome to DashBoard </h1>
</div>

app/views/home/index.html.erb
<div class="container">
  <h1> Welcome to Home Page Book Management System</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookManagementSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="Token" style="display: none" > </div>
  <div class="userID" style="display: none" > </div>
  <div class="userRole" style="display: none"> </div>

  <nav class="navbar navbar-inverse ">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Book System Logo</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
              <li><%= link_to 'Home Page', home_index_path %></li>

              <% if current_user.role == 'admin'%>
                  <li><%= link_to 'User List ', users_path , :method => :get %></li>
              <% end %>
              <li><%= link_to 'Book List ', books_path, :method => :get %></li>
              <li><a data-toggle='modal' data-target='#profile' class="showProfileUser" id="<%= current_user.id %>">Hello <%= current_user.name %></a></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method =>:delete %></li>
          <% else %>
              <li><%= link_to 'Register', register_path, :method => :get %></li>
              <li><%= link_to 'Login', new_user_session_path, :method => :get %></li>
          <%end %>


        </ul>
      </div>
    </div>
  </nav>

    <%= yield %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
  </body>
</html>

app/views/login/index.html.erb
<h1>Index Login</h1>

app/views/login/register.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">

      <form id="signUpForm" method="post">
        <h2>Please Sign Up <small>It's free and always will be.</small></h2>
        <hr class="colorgraph">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <input type="text" name="name" id="name" class="form-control input-lg" placeholder=" User Name" tabindex="1">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-3 col-sm-3 col-md-3">
            <div class="form-group">
              <select name="role" class="custom-select orm-control input-lg">
                <option selected>Roles</option>
                <option value="admin">Admin</option>
                <option value="operator">Operator</option>
              </select>
            </div>
          </div>
        </div>
        <div class="form-group">
          <input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email Address" tabindex="4">
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="5">
            </div>
          </div>
        </div>
        <hr class="colorgraph">
        <div class="row">
          <div class="col-xs-12 col-md-6"><input id="signUpButton" type="button" value="Create Account" class="btn btn-primary btn-block btn-lg " tabindex="7"></div>
          <div class="col-xs-12 col-md-6"><%= link_to 'Cancel', {controller: 'home' , action:'index'}, { class: "btn btn-default btn-block btn-lg" } %></div>
  </div>
      </form>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<style>
  .custab{
    border: 1px solid #ccc;
    padding: 5px;
    margin: 5% 0;
    box-shadow: 3px 3px 2px #ccc;
    transition: 0.5s;
  }
  .custab:hover{
    box-shadow: 3px 3px 0px transparent;
    transition: 0.5s;
  }
</style>

<div id="token" style="display: none" ><%= current_user.api_key.access_token %></div>
<div id="userID" style="display: none" ><%= current_user.id %></div>
<div id="userRole" style="display: none" ><%= current_user.role %></div>

<div class="container">
  <div class="row col-md-10 custyle">
    <table class="table table-striped custab">
      <thead>
      <a id="addUser" data-toggle="modal" data-target="#addUserModel" class="btn btn-primary btn-md pull-right"><b>+</b> Add user</a>
      <tr>
        <th class='text-center'>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th class="text-center">Action</th>
      </tr>
      </thead>
      <tbody id="table_content">

      </tbody>
    </table>
  </div>
</div>



<!--Add User Model-->
<div class="modal fade" id="addUserModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Create User</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name" class="control-label">Name:</label>
            <input type="text" class="form-control" id="name" name="name">
          </div>

          <div class="form-group">
            <label class="control-label">Role:</label>
            <select id="role" name="role" class="custom-select form-control input-xs">
              <option value="operator" selected>Operator</option>
              <option value="admin">Admin</option>
            </select>
          </div>
          <div class="form-group">
            <label for="exampleInputFile">Images upload</label>
            <input name="image" type="file" id="exampleInputFile">
          </div>
          <div class="form-group">
            <label for="email" class="control-label">Email:</label>
            <input type="email" class="form-control" id="email" name="email"></input>
          </div>
          <div class="form-group">
            <label for="password" class="control-label">Password:</label>
            <input type="password" class="form-control" id="password" name="password"></input>
          </div>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="addUserButton" type="button" class="btn btn-primary">Create User </button>
      </div>
    </div>
  </div>
</div>

<!--Edit User Model-->
<div class="modal fade" id="editUserModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Edit User</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name" class="control-label">Name:</label>
            <input type="text" class="form-control" id="name" name="name">
          </div>

          <div class="form-group">
            <label class="control-label">Role:</label>
            <select id="role" name="role" class="custom-select form-control input-xs">
              <option value="operator" selected>Operator</option>
              <option value="admin">Admin</option>
            </select>
          </div>
          <div class="form-group">
            <label for="email" class="control-label">Email:</label>
            <input type="email" class="form-control" id="email" name="email"></input>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="editUserButton" type="button" class="btn btn-primary">Edit User </button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="profile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Profile</h4>
      </div>
      <div class="modal-body">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title" class="Show_Name"></h3>
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                  <div class=" col-md-9 col-lg-9 ">
                    <table class="table table-user-information">
                      <tbody>
                      <tr>
                        <td> ID:</td>
                        <td  class="showID"></td>
                      </tr>
                      <tr>
                        <td> Name:</td>
                        <td  class="showName"></td>
                      </tr>
                      <tr>
                        <td> Email: </td>
                        <td class="showEmail"></td>
                      </tr>
                      <tr>
                        <td > Role: </td>
                        <td class="showRole"></td>
                      </tr>
                      <tr>
                        <td > Created at : </td>
                        <td class="showCreateDate"></td>
                      </tr>
                      <tr>
                        <td > Modified at: </td>
                        <td class="showModifyDate"></td>
                      </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>